# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: truco.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btruco.proto\x12\x0ctrucopackage\x1a\x1bgoogle/protobuf/empty.proto\"G\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05TeamA\x18\x02 \x03(\t\x12\r\n\x05TeamB\x18\x03 \x03(\t\x12\x12\n\nscoreboard\x18\x04 \x03(\x05\"\x15\n\x05Query\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\"\x1c\n\nQueryReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf9\x01\n\x05Truco\x12;\n\nshowTables\x12\x16.google.protobuf.Empty\x1a\x13.trucopackage.Table0\x01\x12\x41\n\x0e\x63reateNewTable\x12\x13.trucopackage.Table\x1a\x18.trucopackage.QueryReply\"\x00\x12\x37\n\tjoinTable\x12\x13.trucopackage.Query\x1a\x13.trucopackage.Query\"\x00\x12\x37\n\texitTable\x12\x13.trucopackage.Query\x1a\x13.trucopackage.Query\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'truco_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TABLE._serialized_start=58
  _TABLE._serialized_end=129
  _QUERY._serialized_start=131
  _QUERY._serialized_end=152
  _QUERYREPLY._serialized_start=154
  _QUERYREPLY._serialized_end=182
  _TRUCO._serialized_start=185
  _TRUCO._serialized_end=434
# @@protoc_insertion_point(module_scope)
