# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import truco_pb2 as truco__pb2


class TrucoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.showTables = channel.unary_stream(
                '/trucopackage.Truco/showTables',
                request_serializer=truco__pb2.Query.SerializeToString,
                response_deserializer=truco__pb2.Table.FromString,
                )
        self.createNewTable = channel.unary_unary(
                '/trucopackage.Truco/createNewTable',
                request_serializer=truco__pb2.Query.SerializeToString,
                response_deserializer=truco__pb2.QueryReply.FromString,
                )
        self.joinTable = channel.unary_unary(
                '/trucopackage.Truco/joinTable',
                request_serializer=truco__pb2.Query.SerializeToString,
                response_deserializer=truco__pb2.QueryReply.FromString,
                )
        self.exitTable = channel.unary_unary(
                '/trucopackage.Truco/exitTable',
                request_serializer=truco__pb2.Query.SerializeToString,
                response_deserializer=truco__pb2.QueryReply.FromString,
                )


class TrucoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def showTables(self, request, context):
        """rpc signin(Query) returns (QueryReply) {};
        rpc signout(Query) returns (QueryReply) {};
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createNewTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def joinTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def exitTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrucoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'showTables': grpc.unary_stream_rpc_method_handler(
                    servicer.showTables,
                    request_deserializer=truco__pb2.Query.FromString,
                    response_serializer=truco__pb2.Table.SerializeToString,
            ),
            'createNewTable': grpc.unary_unary_rpc_method_handler(
                    servicer.createNewTable,
                    request_deserializer=truco__pb2.Query.FromString,
                    response_serializer=truco__pb2.QueryReply.SerializeToString,
            ),
            'joinTable': grpc.unary_unary_rpc_method_handler(
                    servicer.joinTable,
                    request_deserializer=truco__pb2.Query.FromString,
                    response_serializer=truco__pb2.QueryReply.SerializeToString,
            ),
            'exitTable': grpc.unary_unary_rpc_method_handler(
                    servicer.exitTable,
                    request_deserializer=truco__pb2.Query.FromString,
                    response_serializer=truco__pb2.QueryReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trucopackage.Truco', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Truco(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def showTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/trucopackage.Truco/showTables',
            truco__pb2.Query.SerializeToString,
            truco__pb2.Table.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createNewTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trucopackage.Truco/createNewTable',
            truco__pb2.Query.SerializeToString,
            truco__pb2.QueryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def joinTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trucopackage.Truco/joinTable',
            truco__pb2.Query.SerializeToString,
            truco__pb2.QueryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def exitTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trucopackage.Truco/exitTable',
            truco__pb2.Query.SerializeToString,
            truco__pb2.QueryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
